### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tonydu92617** [fblah/fBlahMediaOutput#1]
![1](https://user-images.githubusercontent.com/68638680/108793372-57128680-75be-11eb-913b-e1238d6ad4da.png)
![2](https://user-images.githubusercontent.com/68638680/108793373-5843b380-75be-11eb-8f7a-3d29a80d0585.png)

**Comment by fblah** [comment]
Which version of Unreal Engine 4 are you using?

**Comment by TwoGuysCreative** [comment]
I'm having the same issue... in Unreal 4.26

**Comment by fblah** [comment]
You should update to 4.26.1 because the plugin has been updated to work with that version of UE4

**Comment by TwoGuysCreative** [comment]
Still getting the same issue after updating...

**Comment by fblah** [comment]
Uninstall obs and clear all the files of the plugin.

Install OBS with its required dependencies ([Link](https://obsproject.com/visual-studio-2017-runtimes))

Extract the plugin. (make sure the zip is having the timestamp I uploaded today)

**Comment by TwoGuysCreative** [comment]
Hey =]

OBS is working all good for me with your updated version. But the plugin for UE isn't working, it won't let me open the project, I've updated to the latest version of UE and getting the same dialogues as the start of this opening =]

**Comment by fblah** [comment]
I have uploaded the updated binaries into the repository. Please try it now.

**Comment by TwoGuysCreative** [comment]
Working all good!!! =]
