### ISSUE TITLE
Not showing in OBS studio

### ISSUE THREAD

**Issue by TwoGuysCreative** [fblah/fBlahMediaOutput#2]
Hey, I followed your tutorial to get this into OBS and it's not showing up as a source option...

**Comment by fblah** [comment]
Can you tell me what version of OBS studio you are running?

**Comment by TwoGuysCreative** [comment]
Sure thing!

26.1.1 Windows 64bit

**Comment by fblah** [comment]
I have made an update to the OBS plugin, can you try it out and let me know if the issue persists?

**Comment by TwoGuysCreative** [comment]
Works now thanks!!!
